---
kind: pipeline
name: default

steps:
- name: version
  image: alpine:3.10
  commands:
    - apk add git
    - ./scripts/version > .tags
  when:
    branch:
    - master
    event:
    - push

- name: build
  image: deck15/drone-kaniko:v0.4.2
  when:
    branch:
      excludes: master

- name: publish
  image: deck15/drone-kaniko:v0.4.2
  settings:
    repo: deck15/jq
    username:
      from_secret: docker-username
    password:
      from_secret: docker-password
  when:
    branch:
    - master
    event:
    - push

