---
kind: pipeline
name: default

steps:
- name: version
  image: alpine:3.10
  commands:
    - apk add git
    - ./scripts/version > .tags

- name: publish
  image: deck15/drone-kaniko:v0.4.2
  settings:
    repo: deck15/jq
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  event:
  - tag
...
